CREATE TABLE final_records (
    latitude                         DOUBLE PRECISION NOT NULL,
    longitude                        DOUBLE PRECISION NOT NULL,
    date                             DATE NOT NULL,
    sunrise_iso                      TIMESTAMPTZ,
    sunset_iso                       TIMESTAMPTZ,
    daylight_hours                   DOUBLE PRECISION,

    avg_temperature_2m24h            DOUBLE PRECISION,
    avg_relative_humidity_2m24h      DOUBLE PRECISION,
    avg_dew_point_2m24h              DOUBLE PRECISION,
    avg_apparent_temperature_24h     DOUBLE PRECISION,
    avg_temperature_80m24h           DOUBLE PRECISION,
    avg_temperature_120m24h          DOUBLE PRECISION,
    avg_wind_speed_10m24h            DOUBLE PRECISION,
    avg_wind_speed_80m24h            DOUBLE PRECISION,
    avg_visibility_24h               DOUBLE PRECISION,
    total_rain_24h                   DOUBLE PRECISION,
    total_showers_24h                DOUBLE PRECISION,
    total_snowfall_24h               DOUBLE PRECISION,

    avg_temperature_2m_daylight      DOUBLE PRECISION,
    avg_relative_humidity_2m_daylight DOUBLE PRECISION,
    avg_dew_point_2m_daylight        DOUBLE PRECISION,
    avg_apparent_temperature_daylight DOUBLE PRECISION,
    avg_temperature_80m_daylight     DOUBLE PRECISION,
    avg_temperature_120m_daylight    DOUBLE PRECISION,
    avg_wind_speed_10m_daylight      DOUBLE PRECISION,
    avg_wind_speed_80m_daylight      DOUBLE PRECISION,
    avg_visibility_daylight          DOUBLE PRECISION,
    total_rain_daylight              DOUBLE PRECISION,
    total_showers_daylight           DOUBLE PRECISION,
    total_snowfall_daylight          DOUBLE PRECISION,

    wind_speed_10m_mpers             DOUBLE PRECISION,
    wind_speed_80m_mpers             DOUBLE PRECISION,
    temperature_2m_celsius           DOUBLE PRECISION,
    apparent_temperature_celsius     DOUBLE PRECISION,
    temperature_80m_celsius          DOUBLE PRECISION,
    temperature_120m_celsius         DOUBLE PRECISION,
    soil_temperature_0cm_celsius     DOUBLE PRECISION,
    soil_temperature_6cm_celsius     DOUBLE PRECISION,
    rain_mm                          DOUBLE PRECISION,
    showers_mm                       DOUBLE PRECISION,
    snowfall_mm                      DOUBLE PRECISION,

    fetched_at                       TIMESTAMPTZ DEFAULT NOW(),

    PRIMARY KEY (latitude, longitude, date)
);